-- The earlier prototype schema contains no data in the local development database.
DROP TABLE IF EXISTS "download", "favorite", "template_tag", "submission", "template", "tag", "category", "account", "session", "user" CASCADE;
DROP TYPE IF EXISTS "role", "license", "moderation_status" CASCADE;
CREATE TYPE "content_kind" AS ENUM ('PSD_TEMPLATE', 'REFERENCE', 'DESIGN_BRIEF');
CREATE TYPE "moderation_status" AS ENUM ('PENDING', 'APPROVED', 'REJECTED');
CREATE TYPE "asset_role" AS ENUM ('PSD_SOURCE', 'PREVIEW_IMAGE', 'REFERENCE_IMAGE');
CREATE TYPE "license" AS ENUM ('PERSONAL', 'COMMERCIAL');
CREATE TABLE "user" ("id" text PRIMARY KEY NOT NULL, "name" text NOT NULL, "email" text NOT NULL UNIQUE, "email_verified" boolean DEFAULT false NOT NULL, "image" text, "role" text DEFAULT 'user' NOT NULL, "banned" boolean DEFAULT false, "ban_reason" text, "ban_expires" timestamptz, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE TABLE "session" ("id" text PRIMARY KEY NOT NULL, "expires_at" timestamptz NOT NULL, "token" text NOT NULL UNIQUE, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL, "ip_address" text, "user_agent" text, "user_id" text NOT NULL REFERENCES "user"("id") ON DELETE CASCADE);
CREATE TABLE "account" ("id" text PRIMARY KEY NOT NULL, "account_id" text NOT NULL, "provider_id" text NOT NULL, "user_id" text NOT NULL REFERENCES "user"("id") ON DELETE CASCADE, "access_token" text, "refresh_token" text, "id_token" text, "access_token_expires_at" timestamptz, "refresh_token_expires_at" timestamptz, "scope" text, "password" text, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL, CONSTRAINT "account_provider_account_idx" UNIQUE("provider_id", "account_id"));
CREATE TABLE "verification" ("id" text PRIMARY KEY NOT NULL, "identifier" text NOT NULL, "value" text NOT NULL, "expires_at" timestamptz NOT NULL, "created_at" timestamptz DEFAULT now(), "updated_at" timestamptz DEFAULT now());
CREATE TABLE "category" ("id" text PRIMARY KEY NOT NULL, "name" text NOT NULL, "slug" text NOT NULL UNIQUE, "description" text NOT NULL);
CREATE TABLE "tag" ("id" text PRIMARY KEY NOT NULL, "name" text NOT NULL UNIQUE, "slug" text NOT NULL UNIQUE);
CREATE TABLE "content_item" ("id" text PRIMARY KEY NOT NULL, "kind" "content_kind" NOT NULL, "title" text NOT NULL, "slug" text NOT NULL UNIQUE, "description" text NOT NULL, "category_id" text NOT NULL REFERENCES "category"("id"), "author_id" text NOT NULL REFERENCES "user"("id"), "external_contact_url" text, "dimensions" text, "software_version" text, "license" "license", "moderation_status" "moderation_status" DEFAULT 'PENDING' NOT NULL, "moderation_note" text, "reviewed_by" text REFERENCES "user"("id"), "reviewed_at" timestamptz, "favorites_count" integer DEFAULT 0 NOT NULL, "download_count" integer DEFAULT 0 NOT NULL, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL, "published_at" timestamptz);
CREATE TABLE "content_asset" ("id" text PRIMARY KEY NOT NULL, "content_item_id" text NOT NULL REFERENCES "content_item"("id") ON DELETE CASCADE, "role" "asset_role" NOT NULL, "cloudinary_public_id" text NOT NULL UNIQUE, "cloudinary_version" integer, "resource_type" text NOT NULL, "format" text, "mime_type" text NOT NULL, "bytes" integer NOT NULL, "delivery_type" text NOT NULL, "public_url" text, "created_at" timestamptz DEFAULT now() NOT NULL);
CREATE TABLE "content_tag" ("content_item_id" text NOT NULL REFERENCES "content_item"("id") ON DELETE CASCADE, "tag_id" text NOT NULL REFERENCES "tag"("id") ON DELETE CASCADE, PRIMARY KEY("content_item_id", "tag_id"));
CREATE TABLE "favorite" ("user_id" text NOT NULL REFERENCES "user"("id") ON DELETE CASCADE, "content_item_id" text NOT NULL REFERENCES "content_item"("id") ON DELETE CASCADE, "created_at" timestamptz DEFAULT now() NOT NULL, PRIMARY KEY("user_id", "content_item_id"));
CREATE TABLE "download" ("id" text PRIMARY KEY NOT NULL, "user_id" text REFERENCES "user"("id"), "content_item_id" text NOT NULL REFERENCES "content_item"("id"), "asset_id" text NOT NULL REFERENCES "content_asset"("id"), "created_at" timestamptz DEFAULT now() NOT NULL);
CREATE INDEX "user_role_idx" ON "user" ("role"); CREATE INDEX "session_user_idx" ON "session" ("user_id"); CREATE INDEX "content_catalog_idx" ON "content_item" ("kind", "moderation_status", "created_at"); CREATE INDEX "content_category_idx" ON "content_item" ("category_id", "moderation_status"); CREATE INDEX "content_asset_item_idx" ON "content_asset" ("content_item_id", "role"); CREATE INDEX "download_content_idx" ON "download" ("content_item_id", "created_at");
