"use client";
import axios from "axios";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { api, apiError } from "@/lib/api/client";
const schema = z.object({ kind: z.enum(["PSD_TEMPLATE", "REFERENCE", "DESIGN_BRIEF"]), title: z.string().min(3), description: z.string().min(20), categoryId: z.string().min(1), externalContactUrl: z.string().url().optional().or(z.literal("")), image: z.any(), psd: z.any().optional() });
type Values = z.infer<typeof schema>;
const categories = ["church-flyers", "birthday-flyers", "business-flyers", "party-flyers", "restaurant-flyers", "event-flyers"];
const slugify = (value: string) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
async function upload(file: File, kind: Values["kind"], role: "PSD_SOURCE" | "PREVIEW_IMAGE" | "REFERENCE_IMAGE") { const signature = (await api.post("/uploads/signature", { kind, role, filename: file.name, mimeType: file.type || (role === "PSD_SOURCE" ? "image/vnd.adobe.photoshop" : "image/jpeg") })).data; const data = new FormData(); data.append("file", file); data.append("api_key", signature.apiKey); data.append("timestamp", String(signature.timestamp)); data.append("signature", signature.signature); data.append("folder", signature.folder); data.append("type", signature.type); const result = await axios.post<{ public_id: string }>(signature.uploadUrl, data); return { publicId: result.data.public_id, role }; }
export default function ContributorPage() { const form = useForm<Values>({ resolver: zodResolver(schema), defaultValues: { kind: "PSD_TEMPLATE", categoryId: "church-flyers", title: "", description: "", externalContactUrl: "" } }); const kind = form.watch("kind"); const submit = async (values: Values) => { try { const image = values.image?.[0] as File | undefined; const psd = values.psd?.[0] as File | undefined; if (!image) throw new Error("Choose a JPG, PNG, or WebP image."); if (values.kind === "PSD_TEMPLATE" && !psd) throw new Error("PSD templates require their source PSD file."); const assets = values.kind === "PSD_TEMPLATE" ? [await upload(psd!, values.kind, "PSD_SOURCE"), await upload(image, values.kind, "PREVIEW_IMAGE")] : [await upload(image, values.kind, "REFERENCE_IMAGE")]; await api.post("/content", { kind: values.kind, title: values.title, slug: slugify(values.title), description: values.description, categoryId: values.categoryId, externalContactUrl: values.externalContactUrl || undefined, assets }); form.reset(); form.setError("root", { message: "Submitted for moderation. You will see it once approved." }); } catch (error) { form.setError("root", { message: apiError(error) }); } };
  return <main className="container-page py-12"><div className="max-w-2xl"><p className="eyebrow">Community studio</p><h1 className="mt-3 font-display text-4xl font-bold">Share a template, reference, or design brief.</h1><p className="mt-3 text-muted-foreground">All submissions are reviewed before they become public.</p><form onSubmit={form.handleSubmit(submit)} className="mt-8 space-y-5 rounded-xl border bg-card p-6"><label className="grid gap-2 text-sm font-medium">Content type<select className="h-11 rounded-md border bg-background px-3" {...form.register("kind")}><option value="PSD_TEMPLATE">PSD template</option><option value="REFERENCE">Reference image</option><option value="DESIGN_BRIEF">Design brief</option></select></label><label className="grid gap-2 text-sm font-medium">Title<input className="h-11 rounded-md border bg-background px-3" {...form.register("title")} /></label><label className="grid gap-2 text-sm font-medium">Description<textarea className="min-h-32 rounded-md border bg-background p-3" {...form.register("description")} /></label><label className="grid gap-2 text-sm font-medium">Category<select className="h-11 rounded-md border bg-background px-3" {...form.register("categoryId")}>{categories.map((category) => <option value={category} key={category}>{category.replaceAll("-", " ")}</option>)}</select></label>{kind === "DESIGN_BRIEF" && <label className="grid gap-2 text-sm font-medium">External contact URL<input className="h-11 rounded-md border bg-background px-3" placeholder="https://wa.me/..." {...form.register("externalContactUrl")} /></label>}<label className="grid gap-2 text-sm font-medium">{kind === "PSD_TEMPLATE" ? "Preview image" : "Image"}<input type="file" accept="image/jpeg,image/png,image/webp" {...form.register("image")} /></label>{kind === "PSD_TEMPLATE" && <label className="grid gap-2 text-sm font-medium">PSD source file<input type="file" accept=".psd,image/vnd.adobe.photoshop" {...form.register("psd")} /></label>}{form.formState.errors.root && <p className="text-sm text-destructive">{form.formState.errors.root.message}</p>}<button className="button-primary" disabled={form.formState.isSubmitting}>{form.formState.isSubmitting ? "Uploading…" : "Submit for review"}</button></form></div></main>; }
