"use client";
import Link from "next/link";
import { Download, FolderHeart, Heart, LayoutDashboard, LogOut, Settings, Sparkles, Upload } from "lucide-react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useRouter } from "next/navigation";
import { authClient } from "@/lib/auth-client";
import { api } from "@/lib/api/client";
const links = [[LayoutDashboard,"Dashboard","/dashboard"],[Download,"My Downloads","/dashboard"],[Heart,"Favorites","/favorites"],[FolderHeart,"Collections","/dashboard"],[Settings,"Account Settings","/dashboard/settings"],[Sparkles,"Subscription","/dashboard/subscription"]] as const;
export default function DashboardPage() { const { data: session, isPending } = authClient.useSession(); const router = useRouter(); const queryClient = useQueryClient(); const dashboard = useQuery({ queryKey:["dashboard"], queryFn:async()=> (await api.get("/dashboard")).data.data, enabled:!!session?.user }); const signOut = async () => { await authClient.signOut(); queryClient.clear(); router.replace("/"); router.refresh(); }; if(isPending)return <main className="container-page py-20">Loading your workspace…</main>; if(!session?.user)return <main className="container-page py-20"><h1 className="font-display text-4xl font-bold">Your FlyerHub workspace</h1><Link className="button-primary mt-6" href="/login">Sign in</Link></main>; const data=dashboard.data; return <main className="container-page grid gap-10 py-10 lg:grid-cols-[14rem_1fr]"><aside className="rounded-2xl border border-line p-4"><p className="px-3 font-display text-lg font-bold">FlyerHub</p><Link href="/contributor" className="button-primary mt-5 w-full"><Upload size={16}/>Upload template</Link><nav className="mt-5 space-y-1">{links.map(([Icon,label,href])=><Link key={label} href={href} className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold text-slate-600 hover:bg-indigo-50 hover:text-indigo-700"><Icon size={17}/>{label}</Link>)}<button onClick={signOut} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold text-slate-600 hover:bg-rose-50 hover:text-rose-700"><LogOut size={17}/>Logout</button></nav></aside><section><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Your workspace</p><h1 className="mt-3 font-display text-4xl font-bold">Welcome back, {session.user.name}.</h1></div><Link href="/contributor" className="button-primary"><Upload size={17}/>Upload template</Link></div><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Downloads",data?.downloads,Download],["Favorites",data?.favorites,Heart],["Collections",data?.collections,FolderHeart],["Membership",data?.membership,Sparkles]].map(([label,value,Icon])=>{const I=Icon as typeof Download;return <div key={label as string} className="rounded-2xl border border-line p-5"><I className="text-indigo-600" size={20}/><p className="mt-5 text-2xl font-bold">{value??"—"}</p><p className="mt-1 text-sm text-slate-500">{label as string}</p></div>})}</div><h2 className="mt-10 font-display text-2xl font-bold">Recently downloaded</h2>{data?.recent?.length?<div className="mt-5 space-y-3">{data.recent.map((item:{slug:string;title:string})=><Link href={`/templates/${item.slug}`} key={item.slug} className="block rounded-xl border border-line p-4 font-semibold hover:border-indigo-200">{item.title}</Link>)}</div>:<p className="mt-5 rounded-xl border border-dashed p-8 text-slate-500">Your downloads will appear here. <Link className="font-semibold text-indigo-600" href="/templates">Browse flyers</Link></p>}</section></main>; }
